apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: springboot-github-actions
images:
- name: springboot-github-actions
  newName: maikoncanuto/springboot-github-actions
  newTag: 25.b0436c985a1223eb14622cd0961092e41b6c98c6
