apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
namespace: springboot-github-actions
images:
  - name: springboot-github-actions
    newName: springboot-github-actions
    newTag: latest