apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: springboot-github-actions
images:
- name: springboot-github-actions
  newName: maikoncanuto/springboot-github-actions
  newTag: 26.b484bdbbc812e10ff8ce6018bd16b497e030ab9f
