name: cd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup-jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: build-cache-maven
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: build-maven
        run: mvn -T 1C -B package --file pom.xml

  coverage:
    needs: [ build-and-test ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: mvn -T 1C -B verify --no-transfer-progress

      - uses: codecov/codecov-action@v1
        with:
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov

  release:
    name: release
    runs-on: ubuntu-latest
    needs: [ build-and-test ]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{github.run_number}}.${{github.sha}}
          release_name: Release - ${{github.run_number}}.${{github.sha}}
          draft: false
          prerelease: false

      - name: update-version-release-maven
        run: mvn -T 1C -B versions:set -DnewVersion=${{github.run_number}}.${{github.sha}} -DgenerateBackupPoms=false

      - name: update-version-configure-git
        run: |
          git config user.email "actions@github.com"
          git config user.name "Github Actions"
          git commit -am "Update version maven"
          mvn versions:commit

      - name: push-version-release
        uses: ad-m/github-push-action@master

  publish-package:
    name: publish-package
    runs-on: ubuntu-latest
    needs: [ release ]
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: update-checkout
        run: |
          git pull

      - name: setup-jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: build-cache-maven
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Deploy to Github Package Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir ~/.m2
          echo "<settings><servers><server><id>github</id><username>OWNER</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn deploy

      - name: publish
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  create-image-docker:
    name: create-image-docker
    runs-on: ubuntu-latest
    needs: [ release ]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: update-checkout
        run: |
          git pull

      - name: build-image-docker
        uses: docker/build-push-action@v1.1.0
        with:
          username: maikoncanuto
          password: ${{secrets.DOCKER_PASSWORD}}
          repository: maikoncanuto/springboot-github-actions
          tags: ${{github.run_number}}.${{github.sha}}, latest
