name: cd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup-jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: build-maven
        run: mvn -T 1C -B package --file pom.xml

  release:
    name: release
    runs-on: ubuntu-latest
    needs: [ build-and-test ]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: v${{github.run_number}}
          release_name: Release v${{github.run_number}} - sha:${{github.sha}}

      - name: update-version-release-maven
        run: mvn -T 1C -B versions:set -DnewVersion=${{github.run_number}} -DgenerateBackupPoms=false

      - name: publish-version-maven-github
        run: mvn -T 1C -B deploy -DskipTests --file pom.xml
        env:
          GITHUB_TOKEN: ${{github.token}}

  create-image-docker:
    name: create-image-docker
    runs-on: ubuntu-latest
    needs: [ release ]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build-image-docker
        uses: docker/build-push-action@v1.1.0
        with:
          username: maikoncanuto
          password: ${{secrets.DOCKER_PASSWORD}}
          repository: maikoncanuto/springboot-github-actions
          tags: ${{github.run_number}}, latest
