name: cd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup-jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: build-cache-maven
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: build-maven
        run: mvn -T 1C -B package --file pom.xml

  release:
    name: release
    runs-on: ubuntu-latest
    needs: [ build-and-test ]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{github.run_number}}.${{github.sha}}
          release_name: Release - ${{github.run_number}}.${{github.sha}}
          draft: false
          prerelease: false

      - name: update-version-release-maven
        run: mvn -T 1C -B versions:set -DnewVersion=${{github.run_number}}.${{github.sha}} -DgenerateBackupPoms=false

      - name: update-version-configure-git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git commit -am "Update version maven"
          mvn versions:commit

      - name: push-version-release
        uses: ad-m/github-push-action@master

  create-image-docker:
    name: create-image-docker
    runs-on: ubuntu-latest
    needs: [ release ]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: update-checkout
        run: |
          git pull

      - name: build-image-docker
        uses: docker/build-push-action@v1.1.0
        with:
          username: maikoncanuto
          password: ${{secrets.DOCKER_PASSWORD}}
          repository: maikoncanuto/springboot-github-actions
          tags: ${{github.run_number}}.${{github.sha}}, latest

  deploy-kubernetes:
    name: deploy-kubernetes
    runs-on: ubuntu-latest
    needs: [ create-image-docker ]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: update-checkout
        run: |
          git pull

      - name: kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v3.6.1

      - name: update-kustomize-k8
        run: |
          cd k8s
          kustomize edit set image springboot-github-actions=maikoncanuto/springboot-github-actions:${{github.run_number}}.${{github.sha}}

      - name: commit-k8
        run: |
          git config user.email "actions@github.com"
          git config user.name "Github Actions"
          git config -am "Update k8s kustomize"

      - name: push-k8
        uses: ad-m/github-push-action@master